library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)
welfare<-read.spss(file = "C:/Users/kkang/Desktop/github/Studying-R/Koweps_hpc10_2015_beta1.sav",to.data.frame=T)
welfare<-rename(welfare,sex=h10_g3,birth=h10_g4,marriage=h10_g10,religion=h10_g11,income=p1002_8aq1,code_job=h10_eco9,code_region=h10_reg7)
list_job<-read_excel("C:/Users/kkang/Desktop/github/Studying-R/Koweps_Codebook.xlsx",col_names = T,sheet = 2)
head(list_job)
dim(list_job)
welfare<-left_join(welfare,list_job,id="code_job")
welfare%>%filter(!is.na(code_job))%>%select(code_job,job)%>%head(10)
job_income<-welfare%>%filter(!is.na(job)&!is.na(income))%>%group_by(job)%>%summarise(mean_income=mean(income))
head(job_income)
job_male<-welfare%>%filter(!is.na(job)&sex=="male")%>%group_by(job)%>%summarise(n=n())%>%arrange(desc(n))%>%head(10)
job_female<-welfare%>%filter(!is.na(job)&sex=="female")%>%group_by(job)%>%summarise(n=n())%>%arrange(desc(n))%>%head(10)
job_female
ggplot(data = job_male,aes(x=reorder(job,n),y=n))+geom_col()+coord_flip()
ggplot(data=job_female,aes(x=reorder(job,n),y=n))+geom_col()+coord_flip()
