install.packages("remotes")
remotes::install_github("mrchypark/multilinguer")
library(multilinguer)
install_jdk()
install.packages(c("hash","tau","Sejong","RSQLite","devtools","bit","rex","lazyeval","htmlwidgets","crosstalk","promises","later","sessioninfo","xopen","bit64","blob","DBI","memoise","plogr","covr","DT","rcmdcheck","rversions"),type="binary")
remotes::install_github('haven-jeon/KoNLP', upgrade = "never", INSTALL_opts=c("--no-multiarch"))Use force = TRUE to force installation
library(KoNLP)
library(dplyr)
txt<-readLines("C:/Users/kkang/Desktop/github/Studying-R/hiphop.txt")
head(txt)
library(stringr)
txt<-str_replace_all(txt,"\\W","")
extractNoun("대한민국의 영토는 한반도와 그 부속도서로 한다다")
nouns<-extractNoun(txt)
wordcount<-table(unlist(nouns))
df_word<-as.data.frame(wordcount,stringsAsFactors = F)
df_word<-rename(df_word,word=Var1,freq=freq)
df_word<-filter(df_word,nchar(word)>=2)
install.packages("wordcloud")
library(wordcloud)
library(RColorBrewer)
pal<-brewer.pal(8,"Dark2")
set.seed(1234)
wordcloud(words=df_word$Var1,freq=df_word$Freq,min.freq = 2,max.words = 200,random.order = F,rot.per = 1,scale=c(4,0.3),colors = pal)
pal<-brewer.pal(9,"Blues")[5:9]
set.seed(1234)
wordcloud(words=df_word$Var1,freq=df_word$Freq,min.freq = 2,max.words = 200,random.order = F,rot.per = 1,scale = c(4,0.3),colors = pal)
