exam<-read.csv("C:/Users/kkang/Desktop/R 실습자료/csv_exam.csv")
getwd()
dir()
exam<-read.csv("C:/Users/kkang/Desktop/R 실습자료/csv_exam.txt")
exam
head(exam)
head(exam,10)
tail(exam)
tail(exam,10)
View(exam)
dim(exam)
str(exam)
summary(exam)
install.packages("ggplot2")
library(ggplot2)
mpg<-as.data.frame(ggplot2::mpg)
mpg
View(mpg)
head(mpg)
tail(mpg)
dim(mpg)
str(mpg)
summary(mpg)
?mpg
